apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpserver
spec:
  selector:
    matchLabels:
      run: go-httpserver
  replicas: 1
  template:
    metadata:
      labels:
        run: go-httpserver
    spec:
      containers:
      - name: go-httpserver
        image: cncamp/hpa-example
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: go-httpserver
  labels:
    run: go-httpserver
spec:
  ports:
  - port: 80
  selector:
    run: go-httpserver
