apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-elasticsearch
        image: mirrorgooglecontainers/fluentd-elasticsearch:v2.0.0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

  # 这个 DaemonSet，管理的是一个 fluentd-elasticsearch 镜像的 Pod。
  # 这个镜像的功能：通过 fluentd 将 Docker 容器里的日志转发到 ElasticSearch 中。
  # 可以看到，DaemonSet 跟 Deployment 其实非常相似，只不过是没有 replicas 字段；
  # 它也使用 selector 选择管理所有携带了 name=fluentd-elasticsearch 标签的 Pod。
  # 而这些 Pod 的模板，也是用 template 字段定义的。
  # 在这个字段中，我们定义了一个使用 fluentd-elasticsearch:2.0.0 镜像的容器，
  # 而且这个容器挂载了两个 hostPath 类型的 Volume，分别对应宿主机的 /var/log 目录和 /var/lib/docker/containers 目录。
