apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
  labels:
    name: pv-test
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /test-volume

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: manual
      resources:
        requests:
          storage: 1Gi

# 我们为这个 StatefulSet 额外添加了一个 volumeClaimTemplates 字段。
# 它跟 Deployment 里 Pod 模板（PodTemplate）的作用类似。
# 也就是说，凡是被这个 StatefulSet 管理的 Pod，都会声明一个对应的 PVC；
# 而这个 PVC 的定义，就来自于 volumeClaimTemplates 这个模板字段。
# 更重要的是，这个 PVC 的名字，会被分配一个与这个 Pod 完全一致的编号。

# Reclaim Policy
# Current reclaim policies are:
# Retain -- manual reclamation
# Recycle -- basic scrub (rm -rf /thevolume/*) 
# Delete -- associated storage asset such as AWS EBS, GCE PD, Azure Disk, or OpenStack Cinder volume is deleted
# Currently, only NFS and HostPath support recycling. AWS EBS, GCE PD, Azure Disk, and Cinder volumes support deletion.

#注意要在woker节点创建本地目录 /test-volume
# [root@node1 pv]# kubectl get po
# NAME READY STATUS RESTARTS AGE
# web-0 1/1 Running 0 5m35s
# web-1 0/1 Pending 0 5m32s
# pending是由于 ReadWritOnce 只能让一个pod去挂载使用，而不是一个节点的多个pod挂载使用