apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-storage-app
    label: my-storage-app
  name: my-storage-app
spec:
  containers:
  - image: nginx
    name: my-storage-app
    resources: {}
    volumeMounts:
    - name: task-pv-storage
      mountPath: "/usr/share/nginx/html"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
     claimName: task-pv-claim
status: {}
