# kubectl create secret generic userpass --from-file=./secret-configs/username.txt --from-file=./secret-configs/password.txt
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: userpass
      items:
      - key: username.txt
        path: my-group/my-username

# username secret is stored under /etc/foo/my-group/my-username file instead of /etc/foo/username.
# password secret is not projected.


# [root@VM-0-2-centos pod_demos]# kubectl exec -it mypod /bin/bash
# kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
# root@mypod:/data# ls
# root@mypod:/data# cat  /etc/foo/my-group/my-username
# luoji
# root@mypod:/data# 
