apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume 
spec:
  containers:
  - name: test-secret-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: mysql-cred
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: mysql-cred
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass

#它声明挂载的 Volume，并不是常见的 emptyDir 或者 hostPath 类型，而是 projected 类型。
#这个 Volume 的数据来源（sources），则是名为 user 和 pass 的 Secret 对象，分别对应的是数据库的用户名和密码。
#需要将secret读取出来存放到etcd中
# $ cat ./username.txt
# admin
# $ cat ./password.txt
# c1oudc0w!
# $ kubectl create secret generic user --from-file=./secret-configs/username.txt
# $ kubectl create secret generic pass --from-file=./secret-configs/password.txt
# 更重要的是，像这样通过挂载方式进入到容器里的 Secret，一旦其对应的 Etcd 里的数据被更新，这些 Volume 里的文件内容，同样也会被更新。其实，这是 kubelet 组件在定时维护这些 Volume。

# $ kubectl exec -it test-projected-volume -- /bin/sh
# $ ls /projected-volume/
# user
# pass
# $ cat /projected-volume/user
# root
# $ cat /projected-volume/pass
# 1f2d1e2e67df

# --from-file可以连用，这样password和username就会在一个secret中
# [root@VM-0-2-centos pod_demos]# kubectl create secret generic userpass --from-file=./secret-configs/username.txt --from-file=./secret-configs/password.txt
# secret/userpass created
# [root@VM-0-2-centos pod_demos]# kubectl get secret
# NAME                  TYPE                                  DATA   AGE
# app-secret            Opaque                                1      46d
# default-token-g4954   kubernetes.io/service-account-token   3      296d
# userpass              Opaque                                2      8s
# [root@VM-0-2-centos pod_demos]# kubectl get secret userpass -oyaml
# apiVersion: v1
# data:
#   password.txt: YzFvdWRjMHchCg==
#   username.txt: YWRtaW4K
# kind: Secret
# metadata:
#   creationTimestamp: "2021-09-24T02:30:45Z"
#   name: userpass
#   namespace: default
#   resourceVersion: "30620398"
#   selfLink: /api/v1/namespaces/default/secrets/userpass
#   uid: 6baa4ed6-1cdf-11ec-b5fe-5254006d207c
# type: Opaque

# 这里Opaue代码用户定义的任意数据
# 参考： https://kubernetes.io/docs/concepts/configuration/secret/