apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-database
spec:
  selector:
    matchLabels:
      role: frontend    #只针对带有role: frontend标签的pod
  env:
    - name: DB_PORT
      value: "6379"
  volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website
    role: frontend
spec:
  containers:
    - name: website
      image: nginx:1.8
      ports:
        - containerPort: 80

# 最终运行起来的效果
# $ kubectl get pod website -o yaml
# apiVersion: v1
# kind: Pod
# metadata:
#   name: website
#   labels:
#     app: website
#     role: frontend
#   annotations:
#     podpreset.admission.kubernetes.io/podpreset-allow-database: "resource version"
# spec:
#   containers:
#     - name: website
#       image: nginx
#       volumeMounts:
#         - mountPath: /cache
#           name: cache-volume
#       ports:
#         - containerPort: 80
#       env:
#         - name: DB_PORT
#           value: "6379"
#   volumes:
#     - name: cache-volume
#       emptyDir: {}
