apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume 
spec:
  containers:
  - name: test-secret-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: mysql-cred
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: mysql-cred
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass

#它声明挂载的 Volume，并不是常见的 emptyDir 或者 hostPath 类型，而是 projected 类型。
#这个 Volume 的数据来源（sources），则是名为 user 和 pass 的 Secret 对象，分别对应的是数据库的用户名和密码。
#需要将secret读取出来存放到etcd中
# $ cat ./username.txt
# admin
# $ cat ./password.txt
# c1oudc0w!
# $ kubectl create secret generic user --from-file=./secret-configs/username.txt
# $ kubectl create secret generic pass --from-file=./secret-configs/password.txt
# 更重要的是，像这样通过挂载方式进入到容器里的 Secret，一旦其对应的 Etcd 里的数据被更新，这些 Volume 里的文件内容，同样也会被更新。其实，这是 kubelet 组件在定时维护这些 Volume。

# $ kubectl exec -it test-projected-volume -- /bin/sh
# $ ls /projected-volume/
# user
# pass
# $ cat /projected-volume/user
# root
# $ cat /projected-volume/pass
# 1f2d1e2e67df