#创建一个secret key=key2,value=value3: 
#kubectl create secret generic app-secret --from-literal=key2=value3
#kubectl get secret

#生成一个yaml模板到secret-exsrcise.yaml中
#kubectl run nginx-secret --image=nginx --restart=Never --dry-run=client -oyaml > secret-exsrcise.yaml
# 加入以下配置内容：
# env:
#       - name: NICE_VARIABLE
#         valueFrom:
#           secretKeyRef:
#             name: app-secret
#             key: key2


#启动容器
#kube apply -f secret-exsrcise.yaml

#进入容器查看
#kubectl exec -it nginx-secret -- /bin/bash 

#env命令可以看到NICE_VARIABLE=value3

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secret
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    env:
      - name: NICE_VARIABLE
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: key2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

#创建了一个pod, 名叫nginx-secret，镜像为nginx, 为它设置了一个环境变量，通过secretKey获取
#总结：env配置在和containers的name同级的地方，可以通过secretKeyRef来获取secret中的值
#扩展：如果是configMap,则使用configMapKeyRef来获取configMap中的值