apiVersion: networking.istio.io/v1beta1
kind: VirtualService #VirtualService可以理解为一个高级的Service,访问域名simple.http.io 8088端口就转到destination
metadata:
  name: simple
  namespace: simple
spec:
  gateways:
    - simple
  hosts:
    - simple.http.io
  http:
    - match:
        - port: 8088
      route:
        - destination:
            host: http-server.simple.svc.cluster.local # <servicername>.<namespacename>.svc.cluster.loacal
            port:
              number: 8088
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: simple
  namespace: simple
spec:
  selector:
    istio: ingressgateway  #语义：往打了istio: ingressgateway标签的pod上插入一些规则
  servers:
    - hosts:
        - simple.http.io
      port:
        name: http-simple
        number: 8088
        protocol: HTTP
